"""add movimento_extrato and transacao.conta_id

Revision ID: 3f881d0aa904
Revises: cf59190c319a
Create Date: 2026-07-28 21:17:10.248189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f881d0aa904'
down_revision: Union[str, Sequence[str], None] = 'cf59190c319a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimento_extrato',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('transacao_id', sa.UUID(), nullable=True),
    sa.Column('rendimento_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['rendimento_id'], ['rendimento.id'], ),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transacao', sa.Column('conta_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacao', type_='foreignkey')
    op.drop_column('transacao', 'conta_id')
    op.drop_table('movimento_extrato')
    # ### end Alembic commands ###
