"""add categoria_divida to conta

Revision ID: 5538dba4e069
Revises: b2a9258c1b44
Create Date: 2026-07-29 20:32:33.593437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5538dba4e069'
down_revision: Union[str, Sequence[str], None] = 'b2a9258c1b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta', sa.Column('categoria_divida', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta', 'categoria_divida')
    # ### end Alembic commands ###
