"""add alerta

Revision ID: 55bf72eccf9f
Revises: 88e5136bde47
Create Date: 2026-07-28 14:23:52.097556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bf72eccf9f'
down_revision: Union[str, Sequence[str], None] = '88e5136bde47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('chave_deduplicacao', sa.String(length=120), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('enviado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_deduplicacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerta')
    # ### end Alembic commands ###
