"""add categoria_investimento e grupo encargos financeiros

Revision ID: 6422b67d58c8
Revises: 595756e7a6d5
Create Date: 2026-07-30 23:39:59.395346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from ava.financas.categorias_iniciais import semear_categorias


# revision identifiers, used by Alembic.
revision: str = '6422b67d58c8'
down_revision: Union[str, Sequence[str], None] = '595756e7a6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta', sa.Column('categoria_investimento', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

    # Sementeira idempotente do novo grupo "Encargos financeiros" (ver semear_categorias) —
    # não duplica nada se corrida outra vez, e não mexe nos grupos já existentes.
    semear_categorias(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta', 'categoria_investimento')
    # ### end Alembic commands ###

    # Nota: não remove as categorias/grupo "Encargos financeiros" semeados no upgrade — mesma
    # postura da migração d6f0ed375db0 (sementeira de categorias não se desfaz no downgrade,
    # dados de categoria não são o alvo do que este downgrade reverte).
