"""add fornecedor, transacao, leitura_consumo

Revision ID: 88e5136bde47
Revises: f5d21d646ccc
Create Date: 2026-07-28 00:24:57.362906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e5136bde47'
down_revision: Union[str, Sequence[str], None] = 'f5d21d646ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nif', sa.String(length=9), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('tem_parser_nivel0', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('leitura_consumo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fim', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fornecedor_id', 'periodo_inicio', 'periodo_fim', name='uq_leitura_periodo_fornecedor')
    )
    op.create_table('transacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('titular_id', sa.UUID(), nullable=True),
    sa.Column('registado_por', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ambito', sa.String(length=10), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['registado_por'], ['titular.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(
        'fk_documento_fornecedor_id', 'documento', 'fornecedor', ['fornecedor_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documento_fornecedor_id', 'documento', type_='foreignkey')
    op.drop_table('transacao')
    op.drop_table('leitura_consumo')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
