"""add movimento e movimento_linha

Revision ID: aa0f40c6833b
Revises: d6f0ed375db0
Create Date: 2026-07-30 02:22:29.622755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0f40c6833b'
down_revision: Union[str, Sequence[str], None] = 'd6f0ed375db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('conta_destino_id', sa.UUID(), nullable=True),
    sa.Column('titular_id', sa.UUID(), nullable=True),
    sa.Column('registado_por', sa.UUID(), nullable=True),
    sa.Column('ambito', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('recorrente_id', sa.UUID(), nullable=True),
    sa.Column('linha_extrato_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # nome explícito em todas as FKs (em vez do None gerado por omissão): sem nome,
    # op.drop_constraint no downgrade não consegue identificar a constraint a remover e falha
    # com CompileError "Constraint must have a name" — já aconteceu duas vezes na história
    # deste repositório (ver b2a9258c1b44, categoria_grupo_id_fkey em d6f0ed375db0).
    sa.ForeignKeyConstraint(['conta_destino_id'], ['conta.id'], name='movimento_conta_destino_id_fkey'),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name='movimento_conta_id_fkey'),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], name='movimento_documento_id_fkey'),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], name='movimento_fornecedor_id_fkey'),
    sa.ForeignKeyConstraint(['linha_extrato_id'], ['linha_extrato.id'], name='movimento_linha_extrato_id_fkey'),
    sa.ForeignKeyConstraint(['registado_por'], ['titular.id'], name='movimento_registado_por_fkey'),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.id'], name='movimento_titular_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimento_data'), 'movimento', ['data'], unique=False)
    op.create_index(op.f('ix_movimento_tipo'), 'movimento', ['tipo'], unique=False)
    op.create_table('movimento_linha',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('movimento_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name='movimento_linha_categoria_id_fkey'),
    sa.ForeignKeyConstraint(
        ['movimento_id'], ['movimento.id'], name='movimento_linha_movimento_id_fkey', ondelete='CASCADE'
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimento_linha_movimento_id'), 'movimento_linha', ['movimento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimento_linha_movimento_id'), table_name='movimento_linha')
    op.drop_table('movimento_linha')
    op.drop_index(op.f('ix_movimento_tipo'), table_name='movimento')
    op.drop_index(op.f('ix_movimento_data'), table_name='movimento')
    op.drop_table('movimento')
    # ### end Alembic commands ###
