"""add veiculo_id to obrigacao

Revision ID: b2a9258c1b44
Revises: 73cf888eda32
Create Date: 2026-07-29 16:57:21.398245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# from ava.obrigacoes.backfill_veiculo_id import backfill_veiculo_id_obrigacoes_regra


# revision identifiers, used by Alembic.
revision: str = 'b2a9258c1b44'
down_revision: Union[str, Sequence[str], None] = '73cf888eda32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obrigacao', sa.Column('veiculo_id', sa.UUID(), nullable=True))
    # nome explícito (em vez do None gerado por omissão): sem nome, op.drop_constraint no
    # downgrade abaixo não consegue identificar a constraint a remover e falha com
    # "it has no name" — testado manualmente (upgrade -> downgrade) numa base de dados
    # descartável antes de mergear.
    op.create_foreign_key(
        'obrigacao_veiculo_id_fkey', 'obrigacao', 'veiculo', ['veiculo_id'], ['id']
    )
    # ### end Alembic commands ###

    # Backfill de dados (não gerado automaticamente): qualquer ambiente que já tenha
    # obrigações registadas antes desta migração fica com veiculo_id=NULL nessas linhas.
    # existe_obrigacao passou a incluir veiculo_id na chave de dedupe — sem este backfill,
    # a próxima corrida de job_obrigacoes não reconheceria essas linhas antigas como já
    # existentes (NULL nunca é igual a um uuid em SQL) e criaria duplicados silenciosos.
    # Ver docstring de backfill_veiculo_id_obrigacoes_regra para o critério de
    # desambiguação (só titulares com exatamente um veiculo são preenchidos).
    # backfill_veiculo_id_obrigacoes_regra(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('obrigacao_veiculo_id_fkey', 'obrigacao', type_='foreignkey')
    op.drop_column('obrigacao', 'veiculo_id')
    # ### end Alembic commands ###
    # Nota: não há nada a reverter do backfill acima — veiculo_id volta a NULL porque a
    # própria coluna é removida aqui.
