"""Ativos_e_despesas

Revision ID: ca356e27c264
Revises: f57babb7aacc
Create Date: 2026-08-01 19:05:08.142435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca356e27c264'
down_revision: Union[str, Sequence[str], None] = 'f57babb7aacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Preserve existing data by renaming the table
    op.rename_table('veiculo', 'ativo')
    
    # Add new columns as nullable first
    op.add_column('ativo', sa.Column('tipo', sa.String(length=20), nullable=True))
    op.add_column('ativo', sa.Column('valor_atual', sa.Numeric(precision=12, scale=2), nullable=True))
    
    # Rename matricula to data_aquisicao
    op.alter_column('ativo', 'matricula', new_column_name='data_aquisicao', existing_type=sa.Date(), nullable=True)
    
    # Backfill defaults
    op.execute("UPDATE ativo SET tipo = 'veiculo', valor_atual = 0.00")
    
    # Make columns not null
    op.alter_column('ativo', 'tipo', nullable=False)
    op.alter_column('ativo', 'valor_atual', nullable=False)
    
    # Update movimento_linha
    op.add_column('movimento_linha', sa.Column('ativo_id', sa.UUID(), nullable=True))
    op.add_column('movimento_linha', sa.Column('conta_relacionada_id', sa.UUID(), nullable=True))
    op.add_column('movimento_linha', sa.Column('leitura_odometro', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_movimento_linha_conta_relacionada_id', 'movimento_linha', 'conta', ['conta_relacionada_id'], ['id'])
    op.create_foreign_key('fk_movimento_linha_ativo_id', 'movimento_linha', 'ativo', ['ativo_id'], ['id'])
    
    # Rename veiculo_id in obrigacao and update FK
    op.alter_column('obrigacao', 'veiculo_id', new_column_name='ativo_id', existing_type=sa.UUID())
    op.drop_constraint('obrigacao_veiculo_id_fkey', 'obrigacao', type_='foreignkey')
    op.create_foreign_key('fk_obrigacao_ativo_id', 'obrigacao', 'ativo', ['ativo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update movimento_linha
    op.drop_constraint('fk_movimento_linha_ativo_id', 'movimento_linha', type_='foreignkey')
    op.drop_constraint('fk_movimento_linha_conta_relacionada_id', 'movimento_linha', type_='foreignkey')
    op.drop_column('movimento_linha', 'leitura_odometro')
    op.drop_column('movimento_linha', 'conta_relacionada_id')
    op.drop_column('movimento_linha', 'ativo_id')
    
    # Update obrigacao
    op.drop_constraint('fk_obrigacao_ativo_id', 'obrigacao', type_='foreignkey')
    op.alter_column('obrigacao', 'ativo_id', new_column_name='veiculo_id', existing_type=sa.UUID())
    op.create_foreign_key('obrigacao_veiculo_id_fkey', 'obrigacao', 'ativo', ['veiculo_id'], ['id'])
    
    # Rename ativo back to veiculo
    op.alter_column('ativo', 'data_aquisicao', new_column_name='matricula', existing_type=sa.Date(), nullable=False)
    op.drop_column('ativo', 'valor_atual')
    op.drop_column('ativo', 'tipo')
    op.rename_table('ativo', 'veiculo')
    # ### end Alembic commands ###
