"""add rendimento and rendimento_recorrente

Revision ID: cf59190c319a
Revises: d49fccb4e65b
Create Date: 2026-07-28 21:00:48.723484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf59190c319a'
down_revision: Union[str, Sequence[str], None] = 'd49fccb4e65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendimento_recorrente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titular_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dia_do_mes', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rendimento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titular_id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('recorrente_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['recorrente_id'], ['rendimento_recorrente.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rendimento')
    op.drop_table('rendimento_recorrente')
    # ### end Alembic commands ###
