"""add conta and saldo_historico

Revision ID: d49fccb4e65b
Revises: f3e22692baf6
Create Date: 2026-07-28 20:46:41.501645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49fccb4e65b'
down_revision: Union[str, Sequence[str], None] = 'f3e22692baf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titular_id', sa.UUID(), nullable=False),
    sa.Column('instituicao', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldo_historico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conta_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_id', 'data', name='uq_saldo_conta_data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldo_historico')
    op.drop_table('conta')
    # ### end Alembic commands ###
