"""add categorias

Revision ID: d6f0ed375db0
Revises: 3665d3858ed2
Create Date: 2026-07-30 01:55:02.649687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from ava.financas.categorias_iniciais import semear_categorias


# revision identifiers, used by Alembic.
revision: str = 'd6f0ed375db0'
down_revision: Union[str, Sequence[str], None] = '3665d3858ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('unidade_contador', sa.String(length=10), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    # nome explícito (em vez do None gerado por omissão): sem nome, op.drop_constraint no
    # downgrade abaixo não consegue identificar a constraint a remover e falha com
    # CompileError "Constraint must have a name" — já aconteceu duas vezes na história
    # deste repositório (ver b2a9258c1b44).
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_categoria.id'], name='categoria_grupo_id_fkey'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'nome', name='uq_categoria_grupo_nome')
    )
    # ### end Alembic commands ###

    # Sementeira do conjunto inicial (não gerada automaticamente): 11 grupos e as suas
    # categorias, para que a app arranque com uma taxonomia utilizável em vez de tabelas
    # vazias. Idempotente — ver ava.financas.categorias_iniciais.semear_categorias.
    semear_categorias(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categoria')
    op.drop_table('grupo_categoria')
    # ### end Alembic commands ###
    # Nota: não há nada a reverter da sementeira acima — os dados desaparecem com as
    # próprias tabelas.
