"""fase0 core schema: titular, documento, obrigacao

Revision ID: dc035e5bc70c
Revises: 
Create Date: 2026-07-27 22:47:19.382055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc035e5bc70c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paperless_document_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('nivel_extracao', sa.Integer(), nullable=False),
    sa.Column('estado_validacao', sa.String(length=20), nullable=False),
    sa.Column('dados_extraidos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paperless_document_id', name='uq_documento_paperless_id')
    )
    op.create_table('titular',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obrigacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titular_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_limite', sa.Date(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['titular.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obrigacao')
    op.drop_table('titular')
    op.drop_table('documento')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
