"""telegram attribution: titular chat_id, documento registado_por/ambito, item_fila tipo/contexto

Revision ID: f3e22692baf6
Revises: 55bf72eccf9f
Create Date: 2026-07-28 15:00:03.401578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3e22692baf6'
down_revision: Union[str, Sequence[str], None] = '55bf72eccf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documento', sa.Column('registado_por', sa.UUID(), nullable=True))
    op.add_column('documento', sa.Column('ambito', sa.String(length=10), nullable=False))
    op.create_foreign_key(None, 'documento', 'titular', ['registado_por'], ['id'])
    op.add_column('item_fila', sa.Column('tipo', sa.String(length=20), nullable=False))
    op.add_column('item_fila', sa.Column('contexto', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('item_fila', 'documento_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('titular', sa.Column('telegram_chat_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'titular', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'titular', type_='unique')
    op.drop_column('titular', 'telegram_chat_id')
    op.alter_column('item_fila', 'documento_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('item_fila', 'contexto')
    op.drop_column('item_fila', 'tipo')
    op.drop_constraint(None, 'documento', type_='foreignkey')
    op.drop_column('documento', 'ambito')
    op.drop_column('documento', 'registado_por')
    # ### end Alembic commands ###
