"""add item_fila

Revision ID: f5d21d646ccc
Revises: dc035e5bc70c
Create Date: 2026-07-27 23:32:11.916978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5d21d646ccc'
down_revision: Union[str, Sequence[str], None] = 'dc035e5bc70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_fila',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('texto_ocr', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('resultado_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_fila')
    # ### end Alembic commands ###
