def listar_servicos_homelab() -> list[dict]:
    """Lista dos serviços ativos no servidor Lexius."""
    return [
        {
            "nome": "LiteLLM",
            "categoria": "IA & Modelos",
            "porta": 4000,
            "url": "http://localhost:4000",
            "icone": "🧠",
            "status": "online",
            "descricao": "Gateway de Modelos LLM",
        },
        {
            "nome": "n8n",
            "categoria": "Automação",
            "porta": 5678,
            "url": "http://localhost:5678",
            "icone": "⚡",
            "status": "online",
            "descricao": "Workflows e Automação",
        },
        {
            "nome": "Paperless-ngx",
            "categoria": "Documentos",
            "porta": 8000,
            "url": "http://localhost:8000",
            "icone": "📄",
            "status": "online",
            "descricao": "OCR e Ingestão de Emails",
        },
        {
            "nome": "Nextcloud",
            "categoria": "Cloud Familiar",
            "porta": 8090,
            "url": "http://localhost:8090",
            "icone": "☁️",
            "status": "online",
            "descricao": "Ficheiros e Calendários",
        },
        {
            "nome": "Immich",
            "categoria": "Multimédia",
            "porta": 2283,
            "url": "http://localhost:2283",
            "icone": "🖼️",
            "status": "online",
            "descricao": "Galeria de Fotos com IA",
        },
        {
            "nome": "Vaultwarden",
            "categoria": "Segurança",
            "porta": 8080,
            "url": "http://localhost:8080",
            "icone": "🔐",
            "status": "online",
            "descricao": "Gestor de Passwords",
        },
        {
            "nome": "Syncthing",
            "categoria": "Sincronização",
            "porta": 8384,
            "url": "http://localhost:8384",
            "icone": "🔄",
            "status": "online",
            "descricao": "Sincronização P2P",
        },
        {
            "nome": "Netdata",
            "categoria": "Monitorização",
            "porta": 19999,
            "url": "http://localhost:19999",
            "icone": "📊",
            "status": "online",
            "descricao": "Telemetria em Tempo Real",
        },
        {
            "nome": "Uptime Kuma",
            "categoria": "Monitorização",
            "porta": 3001,
            "url": "http://localhost:3001",
            "icone": "🟢",
            "status": "online",
            "descricao": "Healthcheck de Serviços",
        },
        {
            "nome": "Portainer",
            "categoria": "Infraestrutura",
            "porta": 9443,
            "url": "https://localhost:9443",
            "icone": "🐳",
            "status": "online",
            "descricao": "Gestão de Docker",
        },
    ]
